# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a96c41011f00318cb15baa96ec51b146"
name = "live-cart"
application_url = "https://arm-dawn-attorney-hollywood.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "my18demo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arm-dawn-attorney-hollywood.trycloudflare.com/auth/callback",
  "https://arm-dawn-attorney-hollywood.trycloudflare.com/auth/shopify/callback",
  "https://arm-dawn-attorney-hollywood.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
